name: GitHub-Profile-Summary-Cards

on:
  schedule: # Indented 2 spaces
    - cron: "0 0 * * *" # Indented 4 spaces
  workflow_dispatch: # Indented 2 spaces

jobs: # <-- Make sure this keyword exists and is completely flush left!
  build: # Indented 2 spaces under 'jobs:'
    runs-on: ubuntu-latest # Indented 4 spaces under 'build:'
    allow-empty-commits: false
    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARD_TOKEN }} # Assuming you named your secret PAT
        with:
          USERNAME: ${{ github.repository_owner }}
